name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: artis3n/act-docker-node

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - uses: docker/setup-buildx-action@v1.5.0

      - name: Install Goss
        uses: e1himself/goss-installation-action@v1.0.3
        with:
          version: 'v0.3.15'

      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build the Docker image
        uses: docker/build-push-action@v2.5.0
        with:
          push: false
          tags: ${{ env.IMAGE_NAME }}:test
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Test the image
        run: dgoss run -it -v /var/run/docker.sock:/var/run/docker.sock ${{ env.IMAGE_NAME }}:test
