name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: artis3n/act-docker-node

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Goss
        uses: e1himself/goss-installation-action@v1.0.4
        with:
          version: 'v0.3.16'

      - name: Build and Export
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test the image
        run: dgoss run -it -v /var/run/docker.sock:/var/run/docker.sock ${{ env.IMAGE_NAME }}:test
